### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
It took me a while to realize that the actions needed read and write permissions. So, I think it would be good to add it here.

### CODE REVIEW

**Comment by timovv** [comment]
Thanks for the contribution, and good spotting!  This is new functionality for GitHub Actions, I think. Not sure when it was introduced, but it would break the script for sure.

Maybe instead of a note in the README, we could set the permissions in the `main.yml` action file. According to [these docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs), adding a section like

```yaml
permissions:
  contents: write
```

might do the trick, and then there wouldn’t be any further manual intervention required. If you’re able to make that change I will happily merge that in — otherwise I will take a look later this week, when I get a chance.

**Comment by Trost123** [comment]
Can be closed if https://github.com/timovv/notion-website-template/pull/11 is merged.

**Comment by Trost123** [comment]
@ocular-motor-lab by the way, thanks for creating this PR. If you didn't bring up this topic here, I'd probably spend way more time trying to figure out this issue.

**Comment by timovv** [comment]
Thanks all, I have a terrible memory these days it seems, and never got around to actually do what I promised.

**Pull request closed without merging**
